---
title: "an example of testing with YAML params"
author: "everyone"
date: "`r Sys.time()`"
params:
  test: FALSE
---

```{r setup}
testrmd::init()
testrmd::styles()  # Just temporary--should be automatic
```

## Using YAML to test

By adding `test: TRUE` or `test: FALSE` to your YAML params you can parameterize your test chunks globally. 

```
params:
  test: FALSE
```

To pass this parameter to your test chunks, you use `eval = params$test`.

#### chunk using `params$test`

<!--html_preserve-->
<pre>```{r stopifnot_parameterized, test = TRUE, eval= params$test}
counts <- c(1, 2, 3, 4.5)
stopifnot(
  is.numeric(counts),
  all(counts >= 0),
  isTRUE(all.equal(counts, round(counts)))
)
```</pre><!--/html_preserve-->

#### unparameterized chunk using `test = TRUE`

```{r failing_test, test = TRUE, echo = TRUE}
library(assertthat)
assert_that(is.numeric(y))
```


### testthat

Depends on a patched version, currently `1.0.2.9000`, install via

* `devtools::install_github("hadley/testthat#594")`

```{r testthat_1, test = TRUE}
if ((compareVersion('1.0.2', as.character(packageVersion("testthat")))) == -1) {
  library(testthat)
  testthat::expect_false(FALSE)
  testthat::expect_false(TRUE)
}
```

