---
title: "an example of testing"
author: "everyone"
date: "`r Sys.time()`"
---

```{css}
.testrmd-section {
  padding: 10px;
}
.testrmd-section.pass {
  background-color: #CCFFCC;
}
```

```{r setup}
knitr::knit_hooks$set(
  chunk = function(x, options) {
    if (isTRUE(options$test)) {
      paste0(
        "<div class='testrmd-section pass'>",
        paste(x, collapse = "\n"),
        "</div>"
      )
    } else {
      x
    }
  }
)

run_function <- function(code){
  try(code)
}

knitr::opts_chunk$set(error = TRUE)
```

## Do Some Tests

### assertthat

```{r passing_test, test = TRUE}
library(assertthat)
y <- "hello"

assert_that(is.character(y))
```

```{r failing_test, test = TRUE}
assert_that(is.numeric(y))
```

### assertr

```{r assertr_test, test = TRUE}
library(assertr)
assert_rows(mtcars, num_row_NAs, within_bounds(0,2), mpg:carb)
```

```{r assertr_test2, test = TRUE}
assert_rows(mtcars, num_row_NAs, within_bounds(2,4), mpg:carb)
```

### ensurer
```{r}
library(ensurer)
y <- 3

ensure_that(y, is.numeric)
```

```{r}
ensure_that(y, is.character)
```

### assertive

```{r assertive_test1, test = TRUE}
library(assertive)
counts <- c(1, 2, 3, 4.5)
assert_is_numeric(counts)
assert_all_are_non_negative(counts)
assert_all_are_whole_numbers(counts)
```

### stopifnot

```{r stopifnot_test, test = TRUE}
counts <- c(1, 2, 3, 4.5)
stopifnot(
  is.numeric(counts),
  all(counts >= 0),
  isTRUE(all.equal(counts, round(counts)))
)
```

### validate

Only seems to error out if something is not found ....., can't see how to make
a failure move up to something else, unless we have a custom thing.

```{r validate_test1, test = TRUE}
library(validate)
data(women)

v <- validator(hite < 0, weight > 0)
confront(women, v, raise = "all")
```

### checkmate

```{r checkmate_test1, test = TRUE}
library(checkmate)
checkmate::assert_string("aa", min.chars = 4)
```

```{r checkmate_test2, test = TRUE}
checkmate::assert_string("aaa", min.chars = 2)
```


## Do Some Analysis

```{r}
head(mtcars)
```

